// /js/main.js
import './modules/navigation.js';
import './modules/blog.js';
import './modules/blog-post.js';
import './modules/testimonials.js';
import './modules/equipment.js';
import './modules/contact.js';
import './modules/service-request.js';
import './modules/portfolio.js';
import './modules/admin.js';
import './modules/pricing.js';
import './modules/settings.js';