name: Deploy site to HostGator

on:
  push:
    branches: [ "main" ]  # change if your default branch differs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Pick source and pack safely
        run: |
          set -e
          # If a Website/ folder exists at repo root, deploy that; else deploy repo root
          if [ -d "Website" ]; then SRC="Website"; else SRC="."; fi
          echo "Packaging from: $SRC"

          PKG="$RUNNER_TEMP/package.tgz"
          # Create tar outside the source tree to avoid 'file changed as we read it'
          tar -C "$SRC" -czf "$PKG" \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='.cpanel.yml' \
            .

          # Move into workspace so we have a stable path
          mv "$PKG" "$GITHUB_WORKSPACE/package.tgz"

      - name: Write private key and SSH config
        run: |
          set -e
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.HG_KEY }}" > "$HOME/.ssh/id_hg"
          chmod 600 "$HOME/.ssh/id_hg"

          # Optional known_hosts hardening: skip host key checking for simplicity here
          printf "Host *\n  StrictHostKeyChecking no\n" > "$HOME/.ssh/config"

      - name: Upload package via scp (with legacy KEX/RSA compatibility)
        env:
          HG_HOST: ${{ secrets.HG_HOST }}
          HG_PORT: ${{ secrets.HG_PORT }}
          HG_USER: ${{ secrets.HG_USER }}
        run: |
          set -e
          INBOX="/home/${HG_USER}/deploy_inbox"
          # Ensure inbox exists (via ssh, with same compatibility flags)
          ssh -i "$HOME/.ssh/id_hg" -p "${HG_PORT:-22}" \
            -o KexAlgorithms=diffie-hellman-group-exchange-sha256 \
            -o HostKeyAlgorithms=+ssh-rsa \
            -o PubkeyAcceptedAlgorithms=+ssh-rsa \
            -o Ciphers=aes256-ctr,aes192-ctr,aes128-ctr \
            "${HG_USER}@${HG_HOST}" "mkdir -p \"$INBOX\""

          # Copy the pac
