name: Deploy to Staging (develop → staging.neilsmith.org)

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Place build/minify steps here if you add them later

      - name: Upload to STAGING via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: ${{ secrets.FTP_PORT }}
          local-dir: .
          server-dir: ${{ secrets.FTP_PATH_STAGING }}/
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/*.psd
            **/*.ai
            **/*.zip
            **/*.bak
            **/.vscode/**
            **/.DS_Store
