name: Deploy to Staging (develop → staging.neilsmith.org)

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Sanity: show the directory that will be uploaded
      - name: List workspace root
        run: |
          pwd
          ls -la

      # IMPORTANT: local-dir MUST end with a slash
      - name: Deploy via FTP to staging
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: ./               # <— note the trailing slash required by the action
          server-dir: ${{ secrets.FTP_PATH_STAGING }}/
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/*.psd
            **/*.ai
            **/*.zip
            **/*.bak
            **/.vscode/**
            **/.DS_Store
