name: Deploy site to HostGator

on:
  push:
    branches: ['main']   # change if your default branch is different
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: production  # OPTIONAL: create an Environment named 'production' if you want gates

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Pick source and pack safely
        shell: bash
        run: |
          set -euo pipefail
          if [ -d "Website" ]; then SRC="Website"; else SRC="."; fi
          echo "Packaging from: $SRC"

          PKG="$RUNNER_TEMP/package.tgz"
          # Create tar outside the source tree to avoid 'file changed as we read it'
          tar -C "$SRC" -czf "$PKG" \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='.cpanel.yml' \
            .
          mv "$PKG" "$GITHUB_WORKSPACE/package.tgz"

      - name: Prepare SSH key & known_hosts (pin if provided)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.ssh"
          printf '%s\n' "${{ secrets.HG_KEY }}" > "$HOME/.ssh/id_hg"
          chmod 600 "$HOME/.ssh/id_hg"

          : > "$HOME/.ssh/known_hosts"
          chmod 644 "$HOME/.ssh/known_hosts"

          HG_HOST="${{ secrets.HG_HOST }}"
          HG_PORT="${{ secrets.HG_PORT }}"
          HG_HOST_KEY="${{ secrets.HG_HOST_KEY }}"   # e.g., "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI..."

          if [ -n "$HG_HOST_KEY" ]; then
            printf '%s %s\n' "$HG_HOST" "$HG_HOST_KEY" >> "$HOME/.ssh/known_hosts"
            echo "Pinned host key for $HG_HOST"
          else
            echo "HG_HOST_KEY not set; using ssh-keyscan fallback."
            ssh-keyscan -p "${HG_PORT:-22}" "$HG_HOST" >> "$HOME/.ssh/known_hosts"
          fi

      - name: Upload package via scp (HostGator-compatible KEX/ciphers)
        shell: bash
        env:
          HG_HOST: ${{ secrets.HG_HOST }}      # use your ORIGIN server host (e.g., gatorXXXX.hostgator.com)
          HG_PORT: ${{ secrets.HG_PORT }}
          HG_USER: ${{ secrets.HG_USER }}
        run: |
          set -euo pipefail
          INBOX="/home/${HG_USER}/deploy_inbox"

          SSH_OPTS=(-o BatchMode=yes
                    -o GlobalKnownHostsFile=/dev/null
                    -o UserKnownHostsFile="$HOME/.ssh/known_hosts"
                    -o CheckHostIP=no
                    -o KexAlgorithms=diffie-hellman-group-exchange-sha256
                    -o HostKeyAlgorithms=+ssh-rsa
                    -o PubkeyAcceptedAlgorithms=+ssh-rsa
                    -o Ciphers=aes256-ctr,aes192-ctr,aes128-ctr)

          # Ensure inbox exists
          ssh -i "$HOME/.ssh/id_hg" -p "${HG_PORT:-22}" "${SSH_OPTS[@]}" \
            "${HG_USER}@${HG_HOST}" "mkdir -p \"$INBOX\""

          # Copy the package
          scp -i "$HOME/.ssh/id_hg" -P "${HG_PORT:-22}" "${SSH_OPTS[@]}" \
            package.tgz "${HG_USER}@${HG_HOST}:${INBOX}/package.tgz"

      - name: Publish on server (SSH)
        shell: bash
        env:
          HG_HOST: ${{ secrets.HG_HOST }}
          HG_PORT: ${{ secrets.HG_PORT }}
          HG_USER: ${{ secrets.HG_USER }}
          HG_DOCROOT: ${{ secrets.HG_DOCROOT }}   # e.g., /home4/<user>/public_html
          GIT_SHA: ${{ github.sha }}
        run: |
          set -euo pipefail

          INBOX="/home/${HG_USER}/deploy_inbox"
          STAGE="${INBOX}/unpacked"
          DOCROOT="${HG_DOCROOT}"

          SSH_OPTS=(-o BatchMode=yes
                    -o GlobalKnownHostsFile=/dev/null
                    -o UserKnownHostsFile="$HOME/.ssh/known_hosts"
                    -o CheckHostIP=no
                    -o KexAlgorithms=diffie-hellman-group-exchange-sha256
                    -o HostKeyAlgorithms=+ssh-rsa
                    -o PubkeyAcceptedAlgorithms=+ssh-rsa
                    -o Ciphers=aes256-ctr,aes192-ctr,aes128-ctr)

          ssh -i "$HOME/.ssh/id_hg" -p "${HG_PORT:-22}" "${SSH_OPTS[@]}" \
            "${HG_USER}@${HG_HOST}" bash -lc "
              set -euo pipefail
              DOCROOT=\"${DOCROOT}\"
              INBOX=\"${INBOX}\"
              STAGE=\"${STAGE}\"

              mkdir -p \"\$DOCROOT\" \"\$STAGE\"
              rm -rf \"\$STAGE\" && mkdir -p \"\$STAGE\"

              # Extract uploaded package to stage
              tar -xzf \"\$INBOX/package.tgz\" -C \"\$STAGE\"

              # Require index in stage before touching live
              if [ ! -f \"\$STAGE/index.html\" ] && [ ! -f \"\$STAGE/index.php\" ]; then
                echo 'ERROR: No index.html or index.php in staged content' >&2
                exit 1
              fi

              # Swap contents: clear docroot, then copy staged files
              find \"\$DOCROOT\" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
              cp -a \"\$STAGE\"/. \"\$DOCROOT\"/

              # Cleanup inbox completely
              rm -rf \"\$INBOX\"

              # Permissions
              find \"\$DOCROOT\" -type d -exec chmod 755 {} +
              find \"\$DOCROOT\" -type f -exec chmod 644 {} +

              # Record deployed commit for quick verification
              echo \"${GIT_SHA}\" > \"\$DOCROOT/_deployed.txt\"

              # Final check
              test -f \"\$DOCROOT/index.html\" -o -f \"\$DOCROOT/index.php\"
            "
