name: Mirror to Public Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Remove sensitive files (belt-and-suspenders)
        run: |
          # Extra protection: remove sensitive files even if accidentally committed
          rm -rf config/config.php
          rm -rf secure-config/
          rm -rf php/secrets.php
          rm -rf php/mail_config.php
          rm -f .env
          rm -f .env.*
          rm -f .user.ini
          
          # Remove SQL files (database schemas/data)
          rm -rf sql/
          find . -name "*.sql" -type f -delete
          
          # Remove backup files
          find . -name "*.bak" -type f -delete
          find . -name "*.bak-*" -type f -delete
          
          # Remove logs and storage content (keep .htaccess)
          find php/logs -type f ! -name '.htaccess' -delete 2>/dev/null || true
          find php/storage -type f ! -name '.htaccess' -delete 2>/dev/null || true
          
          echo "✓ Sensitive files removed"

      - name: Push to public repo
        env:
          PUBLIC_REPO: warlikeloki/nsmg-review
          PUBLIC_PUSH_TOKEN: ${{ secrets.PUBLIC_PUSH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Add public repo as remote
          git remote add public https://x-access-token:${PUBLIC_PUSH_TOKEN}@github.com/${PUBLIC_REPO}.git
          
          # Push to public repo (force to ensure clean mirror)
          git push public HEAD:main --force
          
          echo "✓ Successfully mirrored to https://github.com/${PUBLIC_REPO}"