# .github/workflows/mirror-to-public.yml
name: Mirror Private develop → Public main

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      run_from_sha:
        description: 'Optional: SHA to mirror (defaults to latest on develop)'
        required: false
        default: ''

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo @ develop
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: develop

      - name: (Optional) Checkout specific SHA
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_from_sha != '' }}
        run: |
          git checkout ${{ github.event.inputs.run_from_sha }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build filtered tree (exclude sensitive/private files)
        run: |
          mkdir -p /tmp/public
          rsync -a --delete \
            --exclude 'config/config.php' \
            --exclude 'secure-config/' \
            --exclude 'php/secrets.php' \
            --exclude 'php/mail_config.php' \
            --exclude '.env' \
            --exclude '.env.*' \
            --exclude '.user.ini' \
            --exclude 'sql/' \
            --exclude '*.sql' \
            --exclude '*.bak' \
            --exclude '*.bak-*' \
            --exclude 'php/logs/*' \
            --exclude 'php/storage/*' \
            --exclude 'NSMG*.zip' \
            --exclude '*.zip' \
            --exclude 'vendor/' \
            --exclude 'node_modules/' \
            . /tmp/public/

          cd /tmp/public
          git init
          git add -A
          git commit -m "Mirror: filtered export of ${GITHUB_REPOSITORY}@${GITHUB_SHA} (source: develop)"

      - name: Push to public repo (private develop → public main)
        env:
          PUBLIC_REPO: warlikeloki/nsmg-review
          PUBLIC_PUSH_TOKEN: ${{ secrets.PUBLIC_PUSH_TOKEN }}
        run: |
          cd /tmp/public
          # Normalize to a local 'main' branch so the mapping is explicit.
          git branch -M main
          git remote add public "https://x-access-token:${PUBLIC_PUSH_TOKEN}@github.com/${PUBLIC_REPO}.git"
          # Mirror semantics with safety: overwrite public main with this filtered tree.
          git push public main --force-with-lease --tags
          echo "✓ Mirrored private 'develop' to public 'main' at https://github.com/${PUBLIC_REPO}"
